version: '3.8'
services:
  api:
    build:
      context: .  
      dockerfile: ToDoList/Dockerfile
    ports:
      - "8080:8080"  # HTTP
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=tododb;Username=postgres;Password=postgres
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: todo_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
